import canonicalLaneMathlib.AdmissibleClass
import BehavioralSocialSciencesAspectsMathematicsLemmaCanonicalLaneLean.BehavioralBridgeLemmas
import BehavioralSocialSciencesAspectsMathematicsLemmaCanonicalLaneLean.BehavioralGateLemmas

namespace HautevilleHouse
namespace BehavioralSocialSciencesAspectsMathematicsLemmaCanonicalLaneLean

def ConstrainedBehavioralClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_behavioral_endgame (A : AdmissibleClass) : ConstrainedBehavioralClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end BehavioralSocialSciencesAspectsMathematicsLemmaCanonicalLaneLean
end HautevilleHouse